### PR TITLE
Fix websocket subscriptions to not double complete

### PR DESCRIPTION
**Pull request by telemenar**
When I updated from an older version (0.13 ish) to current version one of our unit tests caught that each message id was getting two close messages on websockets. 

It looks like every request was getting one complete from the end of the for loop and then a second complete from the defer function. 

I chose to eliminate the double close by just always relying on the defer for the complete message. 

I have:
 - [x] Added tests covering the bug / feature (see [testing](https://github.com/99designs/gqlgen/blob/master/TESTING.md))
 - [x] Updated any relevant documentation (see [docs](https://github.com/99designs/gqlgen/tree/master/docs/content))

### CODE REVIEW

**Comment by frederikhors** [comment]
I'm not an expert. I just saw that maybe was added here: https://github.com/99designs/gqlgen/pull/1248/files.

**Comment by StevenACoffman** [comment]
@RobinCPel Would you mind reviewing this Websocket PR?

**Comment by telemenar** [comment]
Are the `golangcli-lint` check failures something I need to look at? 

First glance looks like an infra failure to me rather than something relating to the PR? 

But if I’m mid-interpreting the results happy to make changes.

**Comment by StevenACoffman** [comment]
Yeah, I just updated the golangci-lint so hopefully it will be less flaky if you rebase on master.

**Comment by telemenar** [comment]
> I'm not an expert. I just saw that maybe was added here: https://github.com/99designs/gqlgen/pull/1248/files.

Not quite related. That is about closing the socket as a whole. Where as this is about the complete message for a single subscription. 

This was introduced with the patch adding the new subprotocol 
https://github.com/99designs/gqlgen/commit/828820afa95e4e66857839cbcbf6584665cef10c#diff-2741fc2767d8881e164a1ca6a0433035639fe46a8e4a244fb7bfb9e410387fa6R269

**Review by StevenACoffman — APPROVED** [review]

**Comment by StevenACoffman** [comment]
This is a good improvement, and I couldn't figure out how this change could ever possibly be any kind of problem, so I'm merging it now. Thanks very much for this!

**Comment by frederikhors** [comment]
@StevenACoffman can you release this? I'm hacking with subscriptions these days and I can try it.

**Comment by StevenACoffman** [comment]
@frederikhors You should be able to try it out right now without waiting for a release using:
`go get -d github.com/99designs/gqlgen@5a49764956ffb674df2c9bee19455bb1fd3407db`

I would like to release gqlparser, update gqlgen to that release, and maybe get the other two websocket PRs in before the next gqlgen release.

**Comment by telemenar** [comment]
If you want v0.17.2 with just my three changes you can add this line to your go.mod: 

replace github.com/99designs/gqlgen => github.com/observeinc/gqlgen v0.17.2-with3Fixes

**Pull request merged**
