### PR TITLE
`@defer` support

### PR DESCRIPTION
**Pull request by fiatjaf**
This implements `@defer` support according to https://github.com/graphql/graphql-wg/blob/66a80c7e7ff5d881a7de515eec991ca3150c829b/rfcs/DeferStream.md

There are no tests and there may be some bugs yet, but I'm just opening this to ask if this change is desired and/or if the code quality is too bad to be considered -- before I put more time polishing it and writing tests.

(Don't look at the first commit, please, just look at the final result.)

There is a demo app at https://github.com/fiatjaf/gqlgen-defer-demo, you can try it live on https://defer.fiatjaf.com/debug/. Only the fields `availability`, `here` and `there` are concurrent, so they're the only ones that can be deferred (the others will just return in the normal response regardless). Try the query

```graphql
query {
  fruits {
    name
    color
    availability {
      ... on Availability @defer {
        there
      }
      here
    }
  }
}
```

https://user-images.githubusercontent.com/1653275/233782726-97d3f129-e8d6-4190-b6fe-a419bc9809be.mp4

I have:
 - [ ] Added tests covering the bug / feature (see [testing](https://github.com/99designs/gqlgen/blob/master/TESTING.md))
 - [ ] Updated any relevant documentation (see [docs](https://github.com/99designs/gqlgen/tree/master/docs/content))

### CODE REVIEW

**Comment by babymum7** [comment]
Hi is you still working on this

**Comment by fiatjaf** [comment]
I'm waiting for feedback from the maintainers. Meanwhile I'm using this myself.

**Comment by StevenACoffman** [comment]
Sorry, I thought you were still working on it as it doesn't pass existing tests. I would love to have the defer feature supported, but it needs more work  (e.g. passes existing tests) before I would feel comfortable merging it.

Linting the generated code is a good way to find problems in the templates that sometimes are hard to see.

**Comment by fiatjaf** [comment]
Sorry, my time has expired, I don't know when I'll be able to come back to this. Hopefully soon, but if someone else wants to do it instead of me, please do it.

I do get very confused about the amount of examples and test code that exist in the repository. It's hard to understand what each thing is doing.

One question: do we need this to work with HTTP? I had forgotten about that possibility.

And also with `mutation` and `subscription`? My code is only working for `query`, I had forgotten about this too.

**Comment by UnAfraid** [comment]
I made a patch that should fix most of the tests, only one left, but i am not sure how to fix that one.
https://gist.github.com/UnAfraid/35d119480d2f18d9ec43172bc699105b
go generate ./... after applying the patch

**Comment by fiatjaf** [comment]
I am still confused about the role of `root_.gotpl`: https://github.com/99designs/gqlgen/pull/2621

**Comment by UnAfraid** [comment]
I am not sure about it, but its used in a test

**Comment by StevenACoffman** [comment]
@UnAfraid I don't think your patch actually causes the tests to pass? I applied it locally, committed it, and pushed it to a branch (and then I ran `go mod tidy`: https://github.com/99designs/gqlgen/compare/defer_patched?expand=1

Try this:
```
go generate ./...; cd _examples; go generate ./...; cd ..; go test ./...; cd _examples; go generate ./...
```

**Comment by UnAfraid** [comment]
@StevenACoffman here i've made a branch with my changes applied and also latest master changes
https://github.com/99designs/gqlgen/compare/master...UnAfraid:gqlgen:defer?expand=1
There is only one failing test which i am not sure how to address: TestLayouts

**Comment by StevenACoffman** [comment]
Closed in favor of #2642

**Pull request closed without merging**
