### PR TITLE
fix: prevent goroutine leak and CPU spinning at websocket transport

### LINKED ISSUE #2167: Memory Leak at Websocket Transport
### What happened?
There is a memory/goroutine leak at websocket transport

I think this goroutine never closes after client closes was connection. https://github.com/99designs/gqlgen/blob/master/graphql/handler/transport/websocket.go#L374

```go
responses, ctx := c.exec.DispatchOperation(ctx, rc)
for {
       // this never closes even if ctx is done
	response := responses(ctx)
	if response == nil {
		break
	}

	c.sendResponse(msg.id, response)
}
```

### Minimal graphql.schema and models to reproduce
I created a reproduction demo https://github.com/fletcherist/gqlgen-memory-leak

### versions
 - `go run github.com/99designs/gqlgen version` 
 - `go version` go1.17.7 darwin/amd64

Here's some stats
memory-leak

image

I'm working on fix

### PR DESCRIPTION
**Pull request by MoofMonkey**
This fixes #2167 and removes incorrect code merged from PR #2168.

Explanation: while the mentioned PR stopped calling function `responses` after the context was done, it has introduced a new bug -  it doesn't break out of the for loop in case of `response == nil` because `break` now breaks select, not the for loop, which causes goroutine leak and CPU spinning indefinitely.
*I'm not sure yet how to exactly reproduce this behavior, since it doesn't even properly show up in the Golang profiler, but we could see that in production, and only with the mentioned PR. Closing the returned channel helps in the chat example, but not in the more complicated code.

Repro at [fletcherist/gqlgen-memory-leak](https://github.com/fletcherist/gqlgen-memory-leak) is fundamentally flawed because the subscription resolver there [doesn't care about passed context](https://github.com/fletcherist/gqlgen-memory-leak/blob/337041bb77eba22b889d056ffa2e04c71f20bada/graph/schema.resolvers.go#L24-L38) - it doesn't close returned channel (which was required before this PR) and it doesn't end goroutine created there after context cancellation.

Proposed fix: revert mentioned PR and improve subscription channel usage so that the resolver won't have to close it, which is, for example, not done in the [chat example](https://github.com/99designs/gqlgen/blob/8d9d3f125f13dcd19f59072d3c38366dc520758b/_examples/chat/resolvers.go#L135-L151).
It should still be backwards compatible unless the application depended on the fact that the channel will be read after the context cancellation, which is already a problem.

Test case: improved chat example with a check of the amount of goroutines left after many closed subscriptions.
Easiest way to test - cherry-pick commit with changes to the `chat_test.go` or apply all the changes and revert commit with changes to the example itself.

I have:
 - [x] Added tests covering the bug / feature (see [testing](https://github.com/99designs/gqlgen/blob/master/TESTING.md))
 - [ ] Updated any relevant documentation (see [docs](https://github.com/99designs/gqlgen/tree/master/docs/content))

### CODE REVIEW

**Comment by frederikhors** [comment]
@fletcherist

**Comment by fletcherist** [comment]
@MoofMonkey hey. I'm sorry it's my bad, indeed I didn't close the channel after the subscription resolver's context was done. 

> Repro at [fletcherist/gqlgen-memory-leak](https://github.com/fletcherist/gqlgen-memory-leak) is fundamentally flawed because the subscription resolver there [doesn't care about passed context](https://github.com/fletcherist/gqlgen-memory-leak/blob/337041bb77eba22b889d056ffa2e04c71f20bada/graph/schema.resolvers.go#L24-L38) - it doesn't close the returned channel (which was required before this PR) and it doesn't end goroutine created thereafter context cancellation.

I used the [chat](https://github.com/99designs/gqlgen/tree/master/_examples/chat) example to create demo reproduction, where it's also [not handled](https://github.com/99designs/gqlgen/blob/master/_examples/chat/resolvers.go#L135). Closing the channel fixes the issue. That's a pity I missed that thing here and hence in my production code

> Closing the returned channel helps in the chat example, but not in the more complicated code.
Yes I fixed the issue in my prod code by closing channels in the goroutine
Thank you very much for catching this. Hence my PR seems dummy now and should be reverted

**Comment by fletcherist** [comment]
thanks for the great fix

**Comment by frederikhors** [comment]
@StevenACoffman will merge and close this ASAP. Thank you @MoofMonkey, really!

**Comment by StevenACoffman** [comment]
@fletcherist @MoofMonkey it looks like there are some test failures. Can you suggest a fix?

**Comment by MoofMonkey** [comment]
@StevenACoffman I don't really know how to handle keepalives in this test, so I have just added support for keepalives in the websocket client subscriptions. I'm not sure if that's a proper fix, but at least it fixes the chat example. The problem is that it might hang tests with subscriptions, and there's no context parameter in the websocket client to properly handle that.

If gqlgen doesn't like this approach - I can revert keepalives support and simply reduce batch size and subscriptions count in the chat example test, however it'll still sometimes fail to pass if CPU is heavily limited (which is likely for CI).

The other thing that might fail in this test is a random sleep before sending messages, and without this sleep receiving all the messages is not guaranteed, which, I guess, needs to be fixed.
It doesn't seem to be related to my changes to the example since reverting my changes doesn't seem to change anything.

**Comment by MoofMonkey** [comment]
What should I do about the hung test?
The problem, as I wrote before, is in the fact that sleep before posting messages is pretty much random. It doesn't prevent the bug, but only delays it with a race condition of some sort.
There is an option to simply reduce batch size and sleep time, but it won't fix the problem itself.

**Comment by MoofMonkey** [comment]
Looks like the keepalives support doesn't help but just hangs tests, the root cause of the keepalive error is in the subscription race condition.
To test that simply apply the latest revert commit, and increase time.Sleep from 100ms to 1000ms.
To test almost surely get the keepalive error - remove time.Sleep at all.

**Comment by StevenACoffman** [comment]
This is good for getting a new release out, but I would love to have another PR from the WebSocket-using community members like yourself or @RobinCPel to clean this area up better.

**Comment by MoofMonkey** [comment]
I guess that system message should fix the race condition. Is it good enough?
I don't really see any other way to fix it, since the GraphQL server doesn't respond to the subscription by itself.

**Comment by StevenACoffman** [comment]
Thanks for sticking with this! If you see any other opportunities to improve the Websocket / Subscription code, I would love further contributions!

**Comment by StevenACoffman** [comment]
Released in v0.17.9

**Comment by MoofMonkey** [comment]
Thanks for fast responses, merge and release :) 

The only thing that I have left unchecked is that the last commit has revealed a race condition in the chat frontend due to subscriptions data being received before the query is done.
I'll submit a pull request on that in a few minutes, since this one is already marked as merged.

**Pull request merged**
