### PR TITLE
codegen: move templates comments from generated code

### PR DESCRIPTION
**Pull request by a8m**
Template comments should not be included in the generated assets (it repeats itself for every arg).

cc @giautm

### CODE REVIEW

**Comment by a8m** [comment]
Also, something a bit worrying is that the latest upgrade significantly increases the size of the generated code. See this PR as an example (from 15K to 21K): https://github.com/ent/contrib/pull/607/files
image

**Comment by StevenACoffman** [comment]
Ah, oops. Yeah, that's a good call. Not sure about the codegen size increase source (just more comments?).

**Comment by a8m** [comment]
> Not sure about the codegen size increase source (just more comments?).

See the PR example I shared above.

**Comment by StevenACoffman** [comment]
Sorry, I was unclear in my comment.
In https://github.com/ent/contrib/pull/607/files github.com/99designs/gqlgen was moved from v0.17.48 to v0.17.51

In that PR, I see that `entgql/internal/todo/generated.go` went from 15K to 21K lines, but it was not clear to me if the comments fully accounted for the difference.

**Pull request merged**
