### PR TITLE
support to generate model for intermediate interface

### PR DESCRIPTION
**Pull request by Code-Hex**
Describe your PR and link to any relevant issues. 

Closes https://github.com/99designs/gqlgen/issues/1690
I have:
 - [x] Added tests covering the bug / feature (see [testing](https://github.com/99designs/gqlgen/blob/master/TESTING.md))
 - [ ] Updated any relevant documentation (see [docs](https://github.com/99designs/gqlgen/tree/master/docs/content))

I hope "small change, small release". Thanks.

ref: https://github.com/vektah/gqlparser/pull/180

### CODE REVIEW

**Comment by Code-Hex** [comment]
Update the version of the module when only this change is released
https://github.com/vektah/gqlparser/pull/169

**Comment by StevenACoffman** [comment]
Can you look into the test failures?

**Comment by Code-Hex** [comment]
@StevenACoffman this failure caused by gomod.

**Comment by Code-Hex** [comment]
But what happened...

```
.github/workflows/check-fmt
  .github/workflows/check-fmt
  shell: /usr/bin/bash -e {0}
  env:
    GOROOT: /opt/hostedtoolcache/go/1.16.14/x64
go: github.com/99designs/gqlgen@v0.0.0-00010101000000-000000000000 requires
	github.com/vektah/gqlparser/v[2](https://github.com/99designs/gqlgen/runs/5282597021?check_suite_focus=true#step:5:2)@v2.[3](https://github.com/99designs/gqlgen/runs/5282597021?check_suite_focus=true#step:5:3).2-0.20220221192817-3e788[6](https://github.com/99designs/gqlgen/runs/5282597021?check_suite_focus=true#step:5:6)dd3df0: missing go.sum entry; to add it:
	go mod download github.com/vektah/gqlparser/v2
```

**Comment by Code-Hex** [comment]
Probably fixed

**Comment by Code-Hex** [comment]
I need to fix the test for windows... :bow:

**Comment by Code-Hex** [comment]
@StevenACoffman @vektah I have done.
I recommend releasing the gqlparser just contains [`interface implements`](https://github.com/vektah/gqlparser/compare/v2.3.1...master) before merging this PR. and update gqlparset to the version in this PR. Thanks

**Comment by StevenACoffman** [comment]
Thank you for your work, but there's still some lingering work to be done in vektah/gqlparser#181 before we can make a release there.

**Comment by StevenACoffman** [comment]
Waiting on rebase (and probably regenerate?)

**Pull request merged**
