### PR TITLE
Update examples go.mod with appdash replacements

### LINKED ISSUE #2862: Unrecognized import path for sourcegraph/appdash-data
### What happened?
Error building go binary when using this dependency:

```
go: github.com/99designs/gqlgen@v0.10.2 requires sourcegraph.com/sourcegraph/appdash-data@v0.0.0-20151005221446-73f23eafcf67: unrecognized import path "sourcegraph.com/sourcegraph/appdash-data" (parse https://sourcegraph.com/sourcegraph/appdash-data?go-get=1: no go-import meta tags ())
```

### What did you expect?
Able to build.

### versions
 - `go run github.com/99designs/gqlgen version`? v0.10.2
 - `go version`? 1.13

### PR DESCRIPTION
**Pull request by regynald**
Fixes #2862

Added go.mod replacements for Sourcegraph [appdash](https://github.com/sourcegraph/appdash) and [appdash-data](https://github.com/sourcegraph/appdash-data). Ran `go mod tidy` to remove the 404'd URLs from go.sum.

I left tests and documentation as they are, as this shouldn't affect functionality.

### CODE REVIEW

**Comment by UnAfraid** [comment]
This dependency is archived since 2021, we should just remove it in my opinion

**Comment by regynald** [comment]
> This dependency is archived since 2021, we should just remove it in my opinion

Agreed. This is definitely more of a band-aid solution.

**Comment by StevenACoffman** [comment]
```
$ go mod why -m sourcegraph.com/sourcegraph/appdash
# sourcegraph.com/sourcegraph/appdash
github.com/99designs/gqlgen/_examples/chat/server
sourcegraph.com/sourcegraph/appdash
```

**Comment by StevenACoffman** [comment]
I would definitely love someone to contribute a PR to remove this dependency from the example chat server!

**Pull request merged**
