### PR TITLE
Add support for graphql-transport-ws with duplex ping-pong

### PR DESCRIPTION
**Pull request by zdraganov**
Extending this [PR](https://github.com/99designs/gqlgen/pull/1507), included also the duplex ping-pong functionality.

How to use:
```
srv.AddTransport(transport.Websocket{
    PingPongInterval: 5 * time.Second,
    # Other options ...
})

```
Example Apollo client usage:
```
let activeSocket: unknown = null;
let timedOut: unknown = null;

const wsLink = new WebSocketLink({
  url: REACT_APP_GRAPHQL_WS_ENDPOINT as string,
  keepAlive: 10_000, // ping server every 10 seconds
  on: {
    ping: (received) => {
      if (!received) {
        timedOut = setTimeout(() => {
          if (activeSocket && activeSocket.readyState === WebSocket.OPEN) {
            activeSocket.close(4408, 'Request Timeout');
          }
        }, 5_000); // wait 5 seconds for the pong and then close the connection
      }
    },
    pong: (received) => {
      if (received) {
        clearTimeout(timedOut);
      }
    },
  },
});
```

### CODE REVIEW

**Comment by jaredly** [comment]
@zdraganov did you make any substantive changes to #1507, or did you just extend it? It might be nice to merge the other first so I can review the extension in isolation.

**Comment by StevenACoffman** [comment]
@zdraganov I rebased and squash merged  #1507. If you could rebase yours (and add that comment mentioned in  #1507 ) I would appreciate it very much. Thanks!

**Comment by zdraganov** [comment]
Rebased with the master branch.

**Review by jaredly — CHANGES_REQUESTED** [review]
code looks good! Could you add a test or two to `websocket_test.go`?

**Comment by StevenACoffman** [comment]
So when I run this:
```
go generate ./... && cd example/ && go generate ./...
git status
```
I get this:
```
deleted:    ../plugin/resolvergen/testdata/singlefile/out/resolver.go
```
And as a result, I then when I run this:
```
go test -race ./... && cd example && go test -race ./... && cd ..
```
I get a lot of failures which I assume are related. Sorry if I missed that when Jared and I reviewed it earlier (although maybe it's a new problem). Can you please take a look a this so we can get this merged? Thanks!

**Comment by zdraganov** [comment]
Fixed the test, but the generation problem doesn't happens on my side - BigSlur M1
Can you check again?

**Comment by StevenACoffman** [comment]
Huh, well it didn't happen when I refreshed everything and tried it again, so maybe I was on some other branch and they merged weird. 

Thanks!

**Comment by jaredly** [comment]
(It would also be nice to have a test that is "client/server shuts down if pong isn't received within time limit")

**Pull request merged**
