### PR TITLE
Add ContentType to graphql.Upload

### PR DESCRIPTION
**Pull request by yudppp**
Hi, I want to use Upload file `Content-Type`.
So I added this code.

Please check:)

I have:
 - [x] Added tests covering the bug / feature (see [testing](https://github.com/99designs/gqlgen/blob/master/TESTING.md))
 - [x] Updated any relevant documentation (see [docs](https://github.com/99designs/gqlgen/tree/master/docs/content))

ref: https://github.com/99designs/gqlgen/issues/1073

### CODE REVIEW

**Comment by vektah** [comment]
Needs a test and ideally updates to the [documentation](https://gqlgen.com/reference/file-upload/) describing how it would be used.

**Comment by hrb-suzuki** [comment]
Hi @vektah 
I understand it. I wrote document and test code.

**Comment by yudppp** [comment]
Hi @vektah
I understand it. I wrote document and test code.

**Comment by vektah** [comment]
Awesome, thanks for the PR.

**Pull request merged**
