### PR TITLE
Make the resolver implementation configurable via a new template resolver.gotpl

### PR DESCRIPTION
**Pull request by penard-cb**
Describe your PR and link to any relevant issues. 

I'm adding the ability to pass in a new ResolverTemplate to the ResolverConfig which allows the user to configure a new layout and custom template to generate resolvers.

I made #2724 and this PR should fix it.

### What happened?

I need to be able to run gqlgen and pass in a template for generating a resolver. 

I need to be able to pass in new imports and make significant code additions (maybe even some convenience methods). This will allow my implementing team to follow my guidlines. 

### What did you expect?

I thought the config would have an option to just replace the whole gotpl file... it doesn't. 

### Minimal graphql.schema and models to reproduce

```
type Query {
    resolver: Resolver!
}

type Resolver {
    name: String!
}
```

```
schema:
  - "testdata/schema.graphql"

exec:
  filename: testdata/singlefile/out/ignored.go
model:
  filename: testdata/singlefile/out/generated.go
resolver:
  type: CustomResolverType
  layout: follow-schema
  dir: testdata/resolvertemplate/out
  filename_template: "{name}.resolvers.go"
  resolver_template: "testdata/resolvertemplate/customResolverTemplate.gotpl"

models:
  Resolver:
    model: github.com/99designs/gqlgen/plugin/resolvergen/testdata/singlefile/out.Resolver
```

I have:
 - [x] Added tests covering the bug / feature (see [testing](https://github.com/99designs/gqlgen/blob/master/TESTING.md))
 - [x] Updated any relevant documentation (see [docs](https://github.com/99designs/gqlgen/tree/master/docs/content))

### CODE REVIEW

**Comment by StevenACoffman** [comment]
Cool!

**Comment by penard-cb** [comment]
> Cool! I'm looking forward to seeing where this goes. Thanks for working on it!

@StevenACoffman I just pushed an update. I also joined the discord, let me know if you want to chat about it. I think this is ready for review.

**Comment by dmaulick** [comment]
+1 looking forward to this change

**Comment by StevenACoffman** [comment]
@penard-cb I noticed there are some test failures. If you could take a look, I would appreciate it.

**Comment by penard-cb** [comment]
@StevenACoffman Thanks. I was able to run those commands locally and think I found the issue. I pushed up an update. 🤞

**Comment by tsingsun** [comment]
may helpless if not support  customer function in template.

**Comment by penard-cb** [comment]
@tsingsun What do you mean? You can modify the template as you see fit.

**Comment by tsingsun** [comment]
i mean that how to pass the custom function to the template, like use template.Func. 
user custom templates, most likely not just for formatting.

**Comment by penard-cb** [comment]
Hi @tsingsun . Ah I see. Yes, I have a couple of branches where I'm thinking through how to do that. Requires some interesting and substantial refactor though. I will likely continue working on it within the next month. Happy to collaborate if you have some ideas.

**Pull request merged**
