### PR TITLE
fix index generation

### PR DESCRIPTION
**Pull request by vvakame**
https://play.golang.org/p/5R_inyGjapb

### CODE REVIEW

**Comment by vektah** [comment]
The func should probably capture this as an argument:
```go
arr1 = append(arr1, func(idx1 int) graphql.Marshaler {
	// ...
	return arr2
}(idx1))
```

and a test would be nice, this is pretty easy to miss.

**Comment by vvakame** [comment]
Where do you write the test now?

**Comment by vektah** [comment]
If you can do it without changing the schema, use one of the examples.

Otherwise, dump it in https://github.com/99designs/gqlgen/blob/master/codegen/testserver/generated_test.go

**Comment by vvakame** [comment]
this function is an immediate evaluate, it is not a problem even with the original code .... I have just noticed.

**Pull request closed without merging**
