### PR TITLE
federation: generate _entities / _service root queries regardless of …

### PR DESCRIPTION
**Pull request by alexsn**
…entity count

Generate a valid federation schema extention if no object uses @key
directive.

On this case the extension will be defined as follows:
```graphql
union _Entity

type _Service {
  sdl: String
}

extend type Query {
  _entities(representations: [_Any!]!): [_Entity]!
  _service: _Service!
}
```

I have:
 - [x] Added tests covering the bug / feature (see [testing](https://github.com/99designs/gqlgen/blob/master/TESTING.md))

### CODE REVIEW

**Comment by mlaflamm** [comment]
This seems to fix issue #1090. We this haven't been merged?

**Comment by alexsn** [comment]
This sat in review for a long time without any comments. I assumed maintainers were not interested.

**Comment by saminahbab** [comment]
I think this should be reopened, there are legitimate reasons for federating servers even if no object has a @key and so this should be default behaviour

**Comment by kecci** [comment]
i got 422 Unprocessable Entity, is this will be the solution ?

**Pull request closed without merging**
