### PR TITLE
stale

### PR DESCRIPTION
**Pull request by StevenACoffman**
- Prepare for v0.16.0 release
- Add stalebot

### CODE REVIEW

**Comment by frederikhors** [comment]
@StevenACoffman May i ask you why did you add the stale bot again?

Please, that bot just creates clutter.
I am slowly cleaning up all the old issues (closing them or moving them to questions).

Please don't use that bot again. Please.

**Comment by StevenACoffman** [comment]
@frederikhors Sorry, I meant to make this a draft to discuss it with you, but got distracted.

I wondered if this would be helpful after you got through the initial triage, but if not, I'm happy to just close it.

**Comment by frederikhors** [comment]
I've cleaned a lot of new issues, I'm analyzing the old ones.

On some I can't decide because I don't know if it would be more correct to move them to "discussions/ideas" or leave them in the issues and use the labels "idea/rfc/feature-request".

I asked you for your opinion in one of the issues/ideas.

**Comment by mtibben** [comment]
@frederikhors I've personally found the the stalebot an incredibly useful tool for an open source maintainer. Just because an issue isn't open doesn't mean the issue or feature isn't valid. It just means that it's "stale" - no one is interested enough to continue commenting or writing code. 99% of the time this means the feature/issue won't get addressed, and the issue really should be closed. And that's OK. If someone wants to write the code, then it gets re-opened, or a new issue/PR is created. The alternative is an issue list so long it turns into a black hole of out-of-date and irrelevant issues

**Comment by frederikhors** [comment]
I understand your point of view, @mtibben.

My problem with that bot is that it often intervenes in discussions started and not yet finished (with an outcome) because between one comment and another it takes time (free time also to think about it).

I prefer that behind the unintelligent logic of that bot there are us who can reason about what is right and what we are doing (the issues a few days ago were more than 220 or 230 I don't remember).

Do I just need you to decide what to do with the proposals, do we move them to "discussions/ideas" or do we keep them here (in the issues list) with the "proposal" label?

**Comment by frederikhors** [comment]
If you then decide to reactivate that bot, I will adapt to your decision.

**Comment by StevenACoffman** [comment]
Ha, no, if you are willing to actively triage the issues manually, then we don't need the stale bot at all. You've been doing a great job with new issues, but I had wondered if really old issues that no one had commented on for over 365 days should just be closed.

I'm sorry I didn't answer you, but I honestly don't know which would be better and I was going to bring it up with some of the other maintainers in our monthly check-in meeting.

A ton of open issues make people think a project is buggy even if they are all feature requests or ideas, but I also want people to be encouraged to contribute PRs and "fixes issue blah-blah" or "adds feature blah-blah per number so-and-so".

**Comment by mtibben** [comment]
> My problem with that bot is that it often intervenes in discussions started and not yet finished

@frederikhors Stalebot can be configured with a time limit for activity. If a discussion hasn't had a reply in a year (or whatever time limit you consider reasonable), is it really "not yet finished"? And if it's not yet finished, simply re-open, comment, or create a tag for stalebot to ignore.

But totally happy for this stuff to get triaged - I just don't want you to do this for nothing, using your time on issues that will never be seriously looked at again.

Will leave this in your and @StevenACoffman capable hands!

**Pull request closed without merging**
