### PR TITLE
Improve websocket close

### PR DESCRIPTION
**Pull request by maeglindeveloper**
Describe your PR and link to any relevant issues. 

I have:
 - [ ] Added tests covering the bug / feature (see [testing](https://github.com/99designs/gqlgen/blob/master/TESTING.md))
 - [ ] Updated any relevant documentation (see [docs](https://github.com/99designs/gqlgen/tree/master/docs/content))

### CODE REVIEW

**Comment by maeglindeveloper** [comment]
hey @vektah any thoughts on this :) ?

**Comment by maeglindeveloper** [comment]
Hey there, anything I can do to have it merged ? @vektah ? 
Let me know

**Comment by zdraganov** [comment]
Good job!

**Comment by maeglindeveloper** [comment]
@mtibben, I saw that you merged lot of PR this month, could you please review this one ?

**Comment by StevenACoffman** [comment]
@maeglindeveloper if you can add a test for this, I would be happy to merge it! Thanks for your patience while this project was inactive but we're catching up now and would love to have this added in!

**Comment by StevenACoffman** [comment]
@zdraganov what do you think of this PR now that yours has been merged?

**Comment by zdraganov** [comment]
This can be closed. The other [PR](https://github.com/99designs/gqlgen/pull/1578) is covering this and more.

**Comment by StevenACoffman** [comment]
Ok, closing in favor of #1578 but anyone is welcome to open a new PR if there's something missing.

**Pull request closed without merging**
