### PR TITLE
cache control feature

### PR DESCRIPTION
**Pull request by landrade**
At this point, it's been able to write a cache-control structure on extensions and write the cache-control headers based on the lowest cache registered in extensions.

TODO:

- [x] Write precedence hint rules described on apollo documentation
- [x] Validate code design 
- [x] Write tests
- [x] A better example
- [x] Documentation

Reference:

- Issue #737 
- https://www.apollographql.com/docs/apollo-server/performance/caching/
- https://github.com/apollographql/apollo-server/tree/d5015f4ea00cadb2a74b09956344e6f65c084629/packages/apollo-cache-control

I have:
 - [x] Added tests covering the bug / feature (see [testing](https://github.com/99designs/gqlgen/blob/master/TESTING.md))
 - [x] Updated any relevant documentation (see [docs](https://github.com/99designs/gqlgen/tree/master/docs/content))

### CODE REVIEW

**Comment by anupriya17** [comment]
Waiting for this PR to merge

**Comment by bofia** [comment]
Looks very promising - how hard would it be to add support for caching directives?

**Comment by landrade** [comment]
@bofia I've started to implement it, but I removed it from this PR. This PR only contain the required code to make the review easier. 

Please take a look at https://github.com/99designs/gqlgen/pull/1048/commits/cd2ed41370208ba163184108b4c3adebf0abaf25 to get an idea of how it could work.

**Comment by bofia** [comment]
I tried this out and noticed the cache header logic differs slightly from Apollo: when a query has a field with no cache hints, and a field with cache hints, the cache header show set a max-age according to the field with cache hint. However from Apollo's [implementation](https://www.apollographql.com/docs/apollo-server/performance/caching/#setting-a-default-maxage), it should default to 0 (probably to avoid accidental caching of private scopes)

**Comment by vektah** [comment]
This looks great, sorry it's taken so long to review.

Given this is already an extension, we should try to keep this isolated in its own package. Is there anything preventing moving all of this inside `graphql/handler/cache`? 

I guess the biggest complication is that the transports need to be aware of caching to return the correct http headers, perhaps rather than modifying the transport the cache extension can ship with a plain go http middleware?

full updated usage would be along the lines of
```go
cfg := generated.Config{Resolvers: &graph.Resolver{}}
srv := handler.NewDefaultServer(generated.NewExecutableSchema(cfg))
// Enable cache extensions
srv.Use(cache.Extension{})

http.ListenAndServe(":8080", cache.Middleware(srv))
```
and then in resolvers
```go
func (r *commentResolver) Post(ctx context.Context, obj *model.Comment) (*model.Post, error) {
    cache.SetHint(ctx, cache.ScopePublic, 10*time.Second)
    // ..
}
```

**Comment by sandeepone** [comment]
Any update?

**Comment by jakesyl** [comment]
Looks great!

**Comment by landrade** [comment]
Hi People, 
There is a long time that I don't use GQLgen anymore. I'll get the context again of this PR to see what has been missed.

I'm posting a new comment here when it's done.

**Comment by landrade** [comment]
@vektah I've changed the code to follow the API that you recommended. Could you take a look if there are any other suggestions?

To be approved, I need to change the documentation to reflect the new API.

**Comment by anupriya17** [comment]
Is this pr abandoned? Can this be converted into a plugin so that anyone can use it?

Thanks

**Comment by StevenACoffman** [comment]
@anupriya17 yup, it's been abandoned for a long time. If someone wanted to update it and document it, it might still be valuable.

**Comment by landrade** [comment]
Hi @anupriya17, probably yes! 

I've been awaiting some feedback for my changes in my last message, but it's never come. Now I've just noticed that there is more code with conflict =(

Following your suggestion, I extracted this feature into a plugin that you can find here: https://github.com/landrade/gqlgen-cache-control-plugin. Please, feel free to use and contribute with the plugin.

For now, I'm closing this PR.

**Comment by StevenACoffman** [comment]
@landrade I'm so very sorry for your experience. The project was unmaintained for that period of time, but I've been much more actively maintaining it (along with others ) as you can see from the releases over the last few months. 

If you want to just add a PR in the docs describing your plugin, I would merge that right away.

If you are still interested in getting the plugin into this repo, we can help make that happen as well.

**Comment by StevenACoffman** [comment]
@lleadbet This PR had added Apollo cache directive support. I'm not sure if you're interested or able to help, but I wanted to bring it to your attention.

With this plugin, you can write a cache-control HTTP header and cache-control extension, following Apollo's rules. Refs:

- https://www.apollographql.com/docs/apollo-server/performance/caching/
- https://github.com/apollographql/apollo-server/tree/d5015f4ea00cadb2a74b09956344e6f65c084629/packages/apollo-cache-control

**Comment by anupriya17** [comment]
> Hi @anupriya17, probably yes!
> 
> I've been awaiting some feedback for my changes in my last message, but it's never come. Now I've just noticed that there is more code with conflict =(
> 
> Following your suggestion, I extracted this feature into a plugin that you can find here: https://github.com/landrade/gqlgen-cache-control-plugin. Please, feel free to use and contribute with the plugin.
> 
> For now, I'm closing this PR.

Thank you so much for making a plugin.

**Comment by landrade** [comment]
Hi @StevenACoffman, don't worry. I just extracted it into a plugin to release this feature for other people can use it. 

As I said, I'm not using gqlgen for now. So, It's not part of my plans to keep this plugin updated with the new versions of gqlgen.

I can migrate the ownership of the plugin repository for 99designs without any problem. Or I can open a new PR by moving the plugin's code and documentation to this repository. What do you prefer?

I think it could be part of the gqlgen core. This plugin can have advantages in using gqlgen internal code, especially in the transport layer.

**Comment by nikitacrit** [comment]
@landrade Definitely it should be a part of gqlgen. A lot of work has been done, I hope you do this despite the previous bad experience. It's sad to see it left without attention for a few weeks again @StevenACoffman.

**Pull request closed without merging**
