### PR TITLE
Add links to godoc to the README and docsite

### PR DESCRIPTION
**Pull request by ddevault**

### CODE REVIEW

**Comment by ddevault** [comment]
All of the seemingly unrelated changes are for the purpose of (1) moving it to the end of the sidebar and (2) adding a little icon that indicates it's an external link. The result looks like this:

**Comment by vektah** [comment]
I'm not sure how useful godoc is for code generators but if even one person other person gives this a :+1: because they find it useful I'll :shipit:

**Comment by ddevault** [comment]
gqlgen doesn't do *all* of the work for you - you still need to interact with its API from schema.resolvers.go, custom scalars, models, etc.

**Comment by ddevault** [comment]
Thanks :)

**Comment by ddevault** [comment]
It doesn't seem like this change was ever deployed to the website.

**Pull request merged**
