### PR TITLE
Fixed CreateTodo method

### PR DESCRIPTION
**Pull request by Surfoo**

### CODE REVIEW

**Comment by MichaelJCompton** [comment]
Hi, thanks for submitting the PR.

I'm not clear on why this is a 'fix' for the method.  Please supply some context.

**Comment by Surfoo** [comment]
Hello,

Did you really do the whole tutorial?
It's  `rand.Int` from the `crypto` pkg in the generated code, not from `math` pkg.

`rand.Int` on https://golang.org/pkg/crypto/rand/#Int needs `rand io.Reader`, `max *big.Int` in input and returns a `big.Int` and an `error` in output. The actual code in the tutorial doesn't compile.
I assumed we don't care about the error, it's a tutorial :)

And there are still other mistakes inside..

**Comment by Surfoo** [comment]
https://github.com/99designs/gqlgen/issues/1274

**Comment by MichaelJCompton** [comment]
Hi, I think the answer on the issue you linked is what you are looking for:

https://github.com/99designs/gqlgen/issues/1274#issuecomment-734899691

It doesn't say in the tutorial to use `crypto`, but I'll update the text to make it mention `math.rand`. 

I'll close this issue and please report the other errors as new issues so I can track them, thanks.

**Pull request closed without merging**
