### PR TITLE
rename "example" dir to "_examples"

### PR DESCRIPTION
**Pull request by frederikhors**
Should fix https://github.com/99designs/gqlgen/issues/1715. 

I have:
 - [x] Added tests covering the bug / feature (see [testing](https://github.com/99designs/gqlgen/blob/master/TESTING.md))
 - [x] Updated any relevant documentation (see [docs](https://github.com/99designs/gqlgen/tree/master/docs/content))

### CODE REVIEW

**Comment by StevenACoffman** [comment]
So I think you also need to change the github actions and documentation to match to get the test failures to go away?

**Comment by frederikhors** [comment]
@StevenACoffman what this test fails?

```
--- FAIL: TestRewriter (0.11s)
    --- FAIL: TestRewriter/default (0.11s)
        rewriter_test.go:27: 
            	Error Trace:	rewriter_test.go:27
            	Error:      	"[]" should have 2 item(s), but has 0
            	Test:       	TestRewriter/default
```

**Comment by duckbrain** [comment]
@frederikhors  It looks like `internal/rewrite/rewriter_test.go` should be reverted. It was referencing a file named `example.go`, which was not renamed (and is already in a directory named `testdata`, so it doesn't need to be).

**Comment by frederikhors** [comment]
@duckbrain done. What is the problem now?

@StevenACoffman can you please merge this as soon as we understand the remaining problem? I had to fix a lot of conflicts from the master branch.

**Comment by StevenACoffman** [comment]
Sure. If we can get it passing, I'd like to merge it sooner rather than later.

**Comment by frederikhors** [comment]
@StevenACoffman I do not understand what these 2 errors are.

**Comment by duckbrain** [comment]
The Lint/Lint one probably needs running go generate on each of the examples. Because of the rename, go generate ./... will no longer generate the examples, so you'll need to refer to them individually.

The integration/federation one is likely referring to an old path in start.sh. need to look into it more.

**Comment by frederikhors** [comment]
I fixed lint step.

Now only this is the problem:

image

I cannot understand the reason!

**Comment by mtibben** [comment]
```
.github/workflows/check-federation: line 7: ./start.sh: Permission denied
```

Were the permissions for `start.sh` changed? A `chmod 755 start.sh` should fix it

**Comment by frederikhors** [comment]
> ```
> .github/workflows/check-federation: line 7: ./start.sh: Permission denied
> ```
> 
> Were the permissions for `start.sh` changed? A `chmod 755 start.sh` should fix it

Oh! Wow! I'm on Windows. Can you please `chmod` it?

**Comment by mtibben** [comment]
hmmm you should be able to use [WSL](https://docs.microsoft.com/en-us/windows/wsl/)?

**Comment by frederikhors** [comment]
> hmmm you should be able to use [WSL](https://docs.microsoft.com/en-us/windows/wsl/)?

I'm not really in that things... 😢

**Comment by duckbrain** [comment]
@mtibben Good catch.

@frederikhors I don't use Windows, does  `git update-index --chmod=+x _examples/federation/start.sh` do it?

Source https://www.scivision.dev/git-windows-chmod-executable/

**Comment by StevenACoffman** [comment]
FTFY.

**Comment by StevenACoffman** [comment]
One concern is that it is worth highlighting in the directions for contributing code how to run all these checks locally. When they fail, it's not obvious from the github action failures what the problem is.

**Comment by frederikhors** [comment]
Can we merge now?

**Pull request merged**
