### PR TITLE
Implicit external check

### PR DESCRIPTION
**Pull request by jclyons52**
Fixes https://github.com/99designs/gqlgen/issues/2443

As specified in the [Federation v2 documentation](https://www.apollographql.com/docs/federation/federation-2/moving-to-federation-2) The `@external` directive is no longer required for `@key` fields, but it is still required for [@requires](https://www.apollographql.com/docs/federation/entities-advanced/#contributing-computed-entity-fields) and [@provides](https://www.apollographql.com/docs/federation/entities-advanced/#using-provides). When fields are part of the key they should implicitly be considered `@external`. 

This PR updates the `allFieldsAreExternal` method on the entity to take a federation version parameter, if the verstion is set to 2 it checks if the relevant field is is listed in the `@key` directive. If it is, the field is considered external without the `@external` directive.

This PR also requires the `resolvable` argument to the `@key` directive to be set to false for it to consider any fields implicitly external. This is not entirely in line with [the spec](https://www.apollographql.com/docs/federation/subgraph-spec/) as it seems that if `resolvable` is false the entity should be excluded irrespective of what fields are external. In this PR, a less significant departure from the current behavior is favored over correctness as the change would potentially cause existing schemas to start failing.

This PR does not address reference types that have multiple keys defined. from the documentation it seems like a reference type should only use one key directive. All examples show entities with a single key, but the description is ambiguous:
>A subgraph that [references an entity without contributing any fields](https://www.apollographql.com/docs/federation/entities/#referencing-an-entity-without-contributing-fields) can include the fields of any @key in its stub definition

I have:
 - [x] Added tests covering the bug / feature (see [testing](https://github.com/99designs/gqlgen/blob/master/TESTING.md))
 - [x] Updated any relevant documentation (see [docs](https://github.com/99designs/gqlgen/tree/master/docs/content))

### CODE REVIEW

**Comment by jclyons52** [comment]
This may also resolve https://github.com/99designs/gqlgen/issues/2387

**Comment by jclyons52** [comment]
Nevermind the lack of multi key support, that seems like it's broadly an issue that will have to be addressed https://github.com/99designs/gqlgen/issues/1031

**Comment by StevenACoffman** [comment]
Thanks so much! We would love any help on #1031 if you can!

**Comment by jclyons52** [comment]
> Thanks so much! We would love any help on #1031 if you can!

No worries, I'll pick that up next 99time, which is every other Monday

**Comment by jdavisclark** [comment]
awesome. thanks for getting this fixed!

**Pull request merged**
