### PR TITLE
Config option to make resolvers return values instead of pointers

### PR DESCRIPTION
**Pull request by ianling**
https://github.com/99designs/gqlgen/issues/1393

Adds a config option to make resolvers return values instead of pointers.

For example, given the following schema:
```
type User {
  id: ID!
  name: String!
}

type Query {
  user: User!
  maybeUser: User
}
```

Old behavior before this PR (matches default behavior after this PR)
```
func (r *queryResolver) User(ctx context.Context) (*User, error) {
	panic("not implemented")
}

func (r *queryResolver) MaybeUser(ctx context.Context) (*User, error) {
	panic("not implemented")
}
```

New behavior with `resolvers_always_return_pointers: false` (`*User` vs `User` in return type of first function):

```
func (r *queryResolver) User(ctx context.Context) (User, error) {
	panic("not implemented")
}

func (r *queryResolver) MaybeUser(ctx context.Context) (*User, error) {
	panic("not implemented")
}
```

I have:
 - [x] Added tests covering the bug / feature (see [testing](https://github.com/99designs/gqlgen/blob/master/TESTING.md))
 - [x] Updated any relevant documentation (see [docs](https://github.com/99designs/gqlgen/tree/master/docs/content))

### CODE REVIEW

**Comment by ianling** [comment]
Holding until my other PR is finished/merged

**Comment by nikitacrit** [comment]
@ianling Thanks, I'm really looking forward to it. Any predictions when it will be merged?

**Comment by StevenACoffman** [comment]
Sorry! I wanted to let the release sit for a few days for any urgent fixes for the websocket changes (since we don't use those in production at Khan Academy, so I always worry about breaking someone's edge case). I merged the other PR though.

**Comment by ianling** [comment]
Fixed merge conflicts.

Don't be afraid of the large change size, the actual change is only like 1 line, the rest is auto-generated models for tests.

**Comment by ianling** [comment]
Not sure why the Windows tests failed.

**Pull request merged**
