### PR TITLE
fix #2524 basic alias Byte was not binded properly

### LINKED ISSUE #2524: BasicTypes "Byte" Binding for Scalars fails
### What happened?

Since https://github.com/99designs/gqlgen/pull/2486 some common types don't get binded correctly

### What did you expect?
Bytes to be binded to []bytes.

What happens that in this new function introduced in #2486 
https://github.com/99designs/gqlgen/blob/9d22d98c792ba7214dc1aad4366e3f7eba0299f7/internal/code/compare.go#L167

Converts some basic kinds to "similar" types which makes sense in some cases as gqlgen converts Int into multiple types of int.

But in this case where we do the check in :

https://github.com/99designs/gqlgen/blob/9d22d98c792ba7214dc1aad4366e3f7eba0299f7/internal/code/compare.go#L43

It will fail as similar will convert byte -> int64 != byte.

### Minimal graphql.schema and models to reproduce
```
scalar Bytes

type SomeBytesType {
   value: Bytes
}
```

And we add to the gqlgen the scalar + Unmarshal

### versions
 - `go run github.com/99designs/gqlgen version`? 0.17.24
 - `go version`? 1.18

### PR DESCRIPTION
**Pull request by mstephano**
Issue from v0.17.24+ with binding bytes type

Fixes #2524 for basic [alias](https://github.com/golang/go/blob/a11b8e37652ff60302b4a4a55a8a43db6a066ecf/src/go/types/basic.go#L45) `Byte` (proposition from @roneli). Also added tests to make sure binding works properly for:
- basic alias `Rune`
- defined type for []byte
- defined type for []rune

I have:
 - [x] Added tests covering the bug / feature (see [testing](https://github.com/99designs/gqlgen/blob/master/TESTING.md))
 - [ ] Updated any relevant documentation (see [docs](https://github.com/99designs/gqlgen/tree/master/docs/content))

### CODE REVIEW

**Comment by mstephano** [comment]
Should I add some integration tests too to increase the coverage?

**Review by roneli — COMMENTED** [review]
Looks great,  will add as per my comment if we define something like this:

```graphql
scalar StringMap

type SomeStruct {
  field: StringMap
}
```

```go
func MarshalStrMap(val map[string]string) graphql.Marshaler {
	return graphql.WriterFunc(func(w io.Writer) {
		err := json.NewEncoder(w).Encode(val)
		if err != nil {
			panic(err)
		}
	})
}

func UnmarshalStrMap(v interface{}) (map[string]string, error) {
	if m, ok := v.(map[string]string); ok {
		return m, nil
	}

	return nil, fmt.Errorf("%T is not a map", v)
}
```

And we have a struct that is 

```go
type NamedStringType string

type SomeStruct struct{
   Field map[string]NamedStringType
}

```

The generated go will try to use the unrmarshal of the string map but it won't work, since we need to convert the named type to pass to the unmarshaler.

I am trying to figure out in the generator template how to check and fix it.

We can maybe do this in a different PR / I will open an issue about this later today.

**Comment by mstephano** [comment]
@roneli I just tried your code, can you replace `map[string]string` by `map[string]NamedStringType` in your `marshal/unmarshal` func and let me know if that works.

**Comment by roneli** [comment]
> @roneli I just tried your code, can you replace `map[string]string` by `map[string]NamedStringType` in your `marshal/unmarshal` func and let me know if that works.

Yes that will work, but then I need to create an un/marshal for every named type. What I did was force a resolver on the field and convert there. Basically this error will occur if its an external map and you auto bind. (I am doing a lot of auto binding with many many go structs). In that case my simple StringMap isn't enough and I need to create a special map per type.

**Comment by mstephano** [comment]
@roneli Can you create a new issue for the map and describe the improvement you need with code example? I will take a look into it and we can keep our conversation there.

This PR is really to fix for `Byte` for anyone who use it.

**Comment by StevenACoffman** [comment]
Thanks for the fix, and I really appreciate you continuing to work on these issues!

**Pull request merged**
