### PR TITLE
Simplfy concurrent resolver logic

### PR DESCRIPTION
**Pull request by vektah**
Before tackling #275 directly a little cleanup on concurrent resolvers is required. There currently isn't anywhere to add the required checks at the object level.

This pulls the concurrency logic out of individual graphql.Defer functions and moves it up into the object where we can put this bubbling logic. It also moves the recover function into the middleware stack, removing some duplicated code.

### CODE REVIEW

**Comment by dvic** [comment]
@vektah @mathewbyrne shouldn't each item in an array also be resolved in parallel? (see line [here](https://github.com/99designs/gqlgen/blob/master/codegen/object.go#L203)) If not, how would one otherwise benefit from using dataloader implementations? Or am I missing something?

I noticed this when I upgraded to 0.4.x, which caused approximately a 10x increase in the number of SQL queries.

**Comment by dvic** [comment]
@vektah No, the behavior is introduced with this commit, `0.4.4` works fine (produces the same amount of queries as previous versions). It's because of the sync resolving of array elements (done [here](https://github.com/99designs/gqlgen/blob/master/codegen/object.go#L218)). This commit changes the behavior so that resolving a field blocks on returning a `graphql.Marshaler`, while previously this was not the case.

**Comment by dvic** [comment]
@vektah should I open a ticket for this?

**Comment by vektah** [comment]
If you like, I'm hoping to look at it tomorrow.

**Pull request merged**
