### PR TITLE
fix: prevents goroutine leak at websocket transport #2167

### PR DESCRIPTION
**Pull request by fletcherist**
Fixed memory leak described in #2167

I have:
 - [ ] Added tests covering the bug / feature (see [testing](https://github.com/99designs/gqlgen/blob/master/TESTING.md))
 - [ ] Updated any relevant documentation (see [docs](https://github.com/99designs/gqlgen/tree/master/docs/content))

### CODE REVIEW

**Comment by StevenACoffman** [comment]
Thanks for hunting this down!

**Comment by frederikhors** [comment]
@StevenACoffman I think we need to release a PATCH ASAP for this.

**Comment by StevenACoffman** [comment]
@frederikhors In the issue, @fletcherist mentions there is another leak that he is working on identifying and fixing, so I would prefer to wait and give him time to do so and then include both in a new point release.

**Comment by frederikhors** [comment]
Ok, but I think this is already an important PATCH to release because we don't know how much time he needs.

**Pull request merged**
