### PR TITLE
fix #1770 minor error in getting-started.md

### LINKED ISSUE #1770: gqlgen Getting started page wrong?
Hi, I'm totally new to graphql, I found your getting started page and found this: 
image
Is it possible that's wrong? Should UserID be User?

The page is at this link: https://gqlgen.com/getting-started/

### PR DESCRIPTION
**Pull request by fulviodenza**
Fix a minor mistake in getting-started.md

### CODE REVIEW

**Comment by ipfans** [comment]
And there is another PR for docs @StevenACoffman

**Comment by StevenACoffman** [comment]
@ipfans WDYT about this change? the `// fix this line` comment is removed.

**Comment by ipfans** [comment]
@StevenACoffman Oh yes, I think it need to be check

**Comment by StevenACoffman** [comment]
@ipfans Besides the comment removal, do you think that we should otherwise merge this PR, or leave the documentation as is?

**Comment by fulviodenza** [comment]
I created this pr because the example in getting-started did not compile and found it a bit confusing.

**Comment by StevenACoffman** [comment]
Ok, sounds good! Thanks!

**Pull request merged**
